# Generated by Django 4.1.7 on 2023-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
