# Generated by Django 4.1.7 on 2023-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=20)),
            ],
        ),
    ]
