# Generated by Django 4.1.7 on 2023-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
