# Generated by Django 4.1.7 on 2023-02-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('options', models.CharField(max_length=10)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
